### ISSUE TITLE
[Bug]: 企业微信应用通知错误

### ISSUE THREAD

**Issue by AsunaEmiria** [KudouRan/BiliTools#100]
### 运行环境和版本

青龙环境2.13.2

### 发生了什么

企业微信应用通知失败，其他通知方式正常

### 相关的日志输出

```shell
企业微信应用消息发送通知消息失败！！
```

### 相关的配置，注意个人隐私。

```json
QYWX_AM:'xxxxxxx,xxxxx,xxxxx,xxxxx,xxxxx'
```

**Comment by catlair** [comment]
不是很清楚企业微信应用通知，这个是从青龙面板移植的

**Comment by catlair** [comment]
好了，感谢反馈，已经修复。https://github.com/KudouRan/BiliTools/commit/96ee40a0857d0ca5a580e6021416298dbdbe231e
