### ISSUE TITLE
运行时会出现异常: read ECONNRESET

### ISSUE THREAD

**Issue by 26560** [KudouRan/BiliTools#101]
### 运行环境和版本

windows server2012 BiliTools v0.5.220728 node v16.16.0

### 发生了什么

![image](https://user-images.githubusercontent.com/107015987/181795898-8c6c6777-86cf-4cde-8f0c-025636b3324c.png)
![image](https://user-images.githubusercontent.com/107015987/181796019-ff3ea146-4df5-4289-b944-02a69d023215.png)
测试发现大号与小号都会出现这个问题
但是貌似投币异常只在小号出现，而直播功能的异常在大号和小号都会出现。

**Comment by catlair** [comment]
原因未知。可能是网络环境的问题
