### ISSUE TITLE
最新版青龙运行一次后自动禁用任务

### ISSUE THREAD

**Issue by insoxin** [KudouRan/BiliTools#105]
### 运行环境和版本

青龙 2.13.7

### 发生了什么

最新版青龙运行一次后自动禁用任务

### 有效的帮助

这个接口是这样的。。。

**Comment by catlair** [comment]
测试时没有问题的。版本为 2.13.3

![image](https://user-images.githubusercontent.com/44313800/182746658-b19e9a92-8079-4441-b11b-5c450926fdaf.png)

**Comment by insoxin** [comment]
> 2.13.3

2.13.6 我是这个版本

**Comment by insoxin** [comment]
刚刚手动更新到2.13.7

**Comment by catlair** [comment]
2.13.7也没问题。问题是青龙面板造成的，我也无法复现

最好能提供以下信息。

![image](https://user-images.githubusercontent.com/44313800/182748929-a49ca0ec-fa9b-44ea-966f-8640ec99c27f.png)

![image](https://user-images.githubusercontent.com/44313800/182748789-f9c30502-22fa-487e-ae01-2899a4bc657f.png)

**Comment by insoxin** [comment]
![AB6D2267-CAF2-44A8-A2D5-A197AF2074C1](https://user-images.githubusercontent.com/19371836/182749352-d6e0491b-8f48-4c8e-8767-64444dfd77bb.jpeg)

翻了日志,没有报错的,,,,

**Comment by catlair** [comment]
定时规则有问题，你这是直接抄的b站视频的吧。配置一个正常的 cron 表达式。

![image](https://user-images.githubusercontent.com/44313800/182749476-1470eca6-cf9f-4fb6-9908-2d3a9666e13b.png)

**Comment by insoxin** [comment]
> 定时规则有问题，你这是直接抄的b站视频的吧。配置一个正常的 cron 表达式。
> 
> ![image](https://user-images.githubusercontent.com/44313800/182749476-1470eca6-cf9f-4fb6-9908-2d3a9666e13b.png)

对的直接看B站视频……

**Comment by insoxin** [comment]
刚刚我也发现了,已经修改

**Comment by catlair** [comment]
如果依然不行，请重新打开

**Comment by insoxin** [comment]
@catlair  打扰了,该问题又复现了  已经改了定时任务.  很迷...

**Comment by insoxin** [comment]
我手动执行了一下 cookie过期了,请问过期会自动禁用任务吗？

**Comment by KudouRan** [comment]
不太清楚，没有去了解过青龙面板的这些机制

**Comment by KudouRan** [comment]
> 我手动执行了一下 cookie过期了,请问过期会自动禁用任务吗？

应该不是吧，它也没办法知道是否过期

**Comment by insoxin** [comment]
> > 我手动执行了一下 cookie过期了,请问过期会自动禁用任务吗？
> 
> 应该不是吧，它也没办法知道是否过期

我不使用青龙了,换了服务器本地,我看到v0.5.220825  更新介绍有红包功能,请问配置如何开启 

我在https://btdocs.vercel.app/config/#用户配置参考  (多用户参考配置（较全版），可以复制修改后使用，点击查看)


未找到

**Comment by catlair** [comment]
![image](https://user-images.githubusercontent.com/44313800/187055629-32310082-ac5c-4b19-9008-d783c3d322a0.png)

**Comment by insoxin** [comment]
> ![image](https://user-images.githubusercontent.com/44313800/187055629-32310082-ac5c-4b19-9008-d783c3d322a0.png)
> 
> ![image](https://user-images.githubusercontent.com/44313800/187055640-d50fd9c8-7da4-4a76-873f-20751c7ecc9e.png)
> 
> ```js
> {
>   redPack: {
>     // 中场休息时间，当每参加了几个直播间的时候，休息一下 [参加个数，休息时间（分，-1 为直接结束）]
>     restTime: [0, -1],
>     // 同时参与的直播间数量
>     linkRoomNum: 0,
>     // 疑似触发风控时休眠时间（分），-1 为直接结束
>     riskSleepTime: -1,
>     // 总参与次数，达到后不管结果如何，直接结束
>     totalNum: 0,
>     // 参与直播时发送的弹幕数量（与内置数量比，较小者生效）
>     // [固定值]，[最少,最多]
>     dmNum: [5],
>     // 是否在等待时处理关注用户（读取消息，移动）
>     moveUpInWait: true,
>     /** 天选时刻关注 UP 移动到分组 */
>     moveTag: '天选时刻',
>     /** 关注回复处理方式 参考天选 */
>     actFollowMsg: 'read',
>   },
> }
> ```

请问这个在哪里 我在https://btdocs.vercel.app/没找到

**Comment by catlair** [comment]
更新的内容就是在这里看的啊

![image](https://user-images.githubusercontent.com/44313800/187055741-214883a8-072f-47bc-9a8a-e51275173e72.png)

**Comment by insoxin** [comment]
找到了,感谢

**Comment by catlair** [comment]
之所以没写到参考里面，是因为完全没办法搞清楚红包是怎么回事，目前也只是能用而已

**Comment by insoxin** [comment]
> 之所以没写到参考里面，是因为完全没办法搞清楚红包是怎么回事，目前也只是能用而已

这个红包,我去年写过
个人遇到的 这活动链接经常消失又出现新链接不固定需要重新抓包,然后我一个五级号因为24小时不断抽红包,再送小号套现,大概搞了几百块.然后被永封了,再注册新号继续搞的时候,发现每天抽再多有中奖限制数量就没搞了

![8E6E7E6F-C2A3-4EA3-9E95-18AA21DC9E13](https://user-images.githubusercontent.com/19371836/187056112-ed13ee07-863a-4be1-9442-d1fc01294f2a.jpeg)

**Comment by insoxin** [comment]
如果大佬您是因为获取红包房间链接经常变 这个问题,我的解决办法是自己手写API中转经常官方变的这个.而不改变已经发布的程序

**Comment by catlair** [comment]
不是通过活动链接进行的，不存在这个问题。是b站现在对这些风控比较严格
