### ISSUE TITLE
[新增]:希望cookie能自己更新 

### ISSUE THREAD

**Issue by AQUOSZZY** [KudouRan/BiliTools#110]
### 需求描述

我在云函数上运行几天之后cookie就失效登录不了了，重新在浏览器里提取cookie更新才能用，是因为B站的cookie的有效时间只有几天吗？（小白用户不太懂）

### 有效的帮助

这个接口是这样的。。。

**Comment by catlair** [comment]
文档有这个说明。自动更新会增加云函数的使用难度

**Comment by AQUOSZZY** [comment]
> 文档有这个说明，cookie 不会凭白无故刷新的。自动更新会增加云函数的使用难度

好的

**Comment by catlair** [comment]
![Uploading Screenshot_2022-08-09-12-54-43-190_com.microsoft.emmx.jpg…]()

**Comment by catlair** [comment]
![image](https://user-images.githubusercontent.com/44313800/183578864-6fb4bd4d-5d85-44c7-951e-2d11fed15f55.png)
