### ISSUE TITLE
[新增]: 请问下可以做观看直播时长的任务吗

### ISSUE THREAD

**Issue by suka233** [KudouRan/BiliTools#83]
### 需求是否是平台独享受的

非云函数环境

### 需求描述

B站有个观看直播时长的任务,只要在指定直播间待够几个小时,就能获取奖励.
具体来说,就是饥荒这个游戏,在指定的直播间看满6个小时直播,就能获取游戏道具

### 有效的帮助

示例直播间:https://live.bilibili.com/10064317

查看已经挂了多久时长的页面:https://live.bilibili.com/blackboard/starve-2020-pc.html

**Comment by catlair** [comment]
可以试一下用现成的可不可以，如果不行就算了，不想做。

**Comment by suka233** [comment]
> 可以试一下用现成的可不可以，如果不行就算了，不想做。

嗯嗯好的 感谢~

**Comment by KudouRan** [comment]
![图片](https://user-images.githubusercontent.com/81743795/177154051-dd88ff92-5b9f-4ad0-b719-fe0184e89ba9.png)

![图片](https://user-images.githubusercontent.com/81743795/177154101-1f4bdf94-697c-4b31-90b9-7d411fefc046.png)

很抱歉，我没有这游戏，无法绑定也就无法知道现成的接口行不行

```bash
npm install @catlair/bilitools@beta
```

https://github.com/KudouRan/BiliTools/releases/tag/v0.5.220705-rc0

**Comment by KudouRan** [comment]
不知是否有效果，暂时关闭
