### ISSUE TITLE
[Bug]: 青龙运行v0.5.220708版本异常

### ISSUE THREAD

**Issue by Night-stars-1** [KudouRan/BiliTools#84]
### 是否已经阅读文档

- [x] 我确定阅读过文档

### 运行环境

青龙

### 发生了什么

青龙运行v0.5.220708版本无法登录
运行v0.5.220628版本则正常登录
![IMG_20220710_125602](https://user-images.githubusercontent.com/99261160/178131948-a032a53f-5955-419d-ba60-609db1904fd9.jpg)

![Screenshot_2022-07-10-12-56-57-606_com android chrome](https://user-images.githubusercontent.com/99261160/178131964-581e4bcb-4ea0-45ea-b4ef-90f0ef26e76f.png)

### 版本

v0.5.220708

### 相关的日志输出

```shell
## 开始执行... 2022-07-10 00:28:53

[💬 00:28:53] 读取配置文件 /ql/data/scripts/cat_bili_config1.json
正在执行第1/1个配置
[👻 00:28:53] 当前版本【v0.5.220708】
[👻 00:28:54] ----【登录】----
[❓ 00:28:54] 登录错误 -101 账号未登录
[❓ 00:28:54] 登录失败: Error: 账号未登录
[👻 00:28:54] ----【消息推送】----
[👻 00:28:55] Telegram发送通知消息成功🎉。
执行完毕


## 执行结束... 2022-07-10 00:28:55 耗时 2 秒
```

**Comment by catlair** [comment]
退回0.5.220628可以吗，安装的依赖或者自动更新那里把 `@catlair/bilitools` 改成 `@catlair/bilitools@0.5.220628` 就能指定版本

**Comment by Night-stars-1** [comment]
> 

我是发现v0.5.220708版本无法登录退回v0.5.220628版本的(v0.5.220708版本登录正常)，所以cookie应该是有效的

SESSDATA是第一种格式(b0514d76%2C1672929334%2Ce6986*71)

**Comment by Night-stars-1** [comment]
> 退回0.5.220628可以吗，安装的依赖或者自动更新那里把 `@catlair/bilitools` 改成 `@catlair/bilitools@0.5.220628` 就能指定版本
> 
> 还是说已经退回了。
> 
> 可以尝试更新 cookie，如果确定 cookie 是有效的，我希望知道cookie中的SESSDATA是
> 
> 1. `1236efe68%2C1672532137%2Cf0519*71`
> 2. `1236efe68,1672532137,f0519*71`
> 3. `1236efe68%2C1672532137%2Cf0519%2A71`
>    中的哪里一种格式，谢谢

很抱歉刚刚才看见回复
我是发现v0.5.220708版本无法登录之后退回v0.5.220628版本的(v0.5.220708版本登录正常)，所以cookie应该是有效的

SESSDATA是第一种格式(b0514d76%2C1672929334%2Ce6986*71)

**Comment by catlair** [comment]
这确实令人匪夷所思。

更新中有以下两个提交会影响到登录，但是我用了几个账号各种方式获取的 cookie 测试并没有复现这个问题。

![image](https://user-images.githubusercontent.com/44313800/178149423-54d1e891-99f4-43ef-860a-f243db26411b.png)

我可能需要更多有用的信息，比如使用的完整的 cookie 。类似于下面这样，除了必要的内容 `DedeUserID=1111111111111111; DedeUserID__ckMd5=xxxxxxxxxxxxxxx; SESSDATA=xxxxxxx%2C111111111%2Cxxxxx*11; bili_jct=xxxxxxxxxxxxxxxxxxxxxxxx;` 屏蔽外，其它都保持原状。

`_uuid=57410536E-54ED-F9FB-E1D6-5F5DD615728333965infoc; buvid4=5A9EF03F-1B37-C000-F9FF-5102AC0A136232033-022030520-VvMikCQsMQZlpg2xGrb53Q%3D%3D; buvid_fp_plain=undefined; CURRENT_BLACKGAP=0; rpdid=|(k))JlJmu~l0J'uYRYR)Rl)|; LIVE_BUVID=AUTO9516464848864875; nostalgia_conf=-1; hit-dyn-v2=1; is-2022-channel=1; blackside_state=0; buvid_fp=ac1cd9b03dee8a9ebdf8f917ed9e8148; CURRENT_QUALITY=120; sid=aask0sb4; buvid3=A7270DDC-668C-414A-8B4F-7C3744100901167636infoc; fingerprint3=1093ceb29f559ff6ab9a3b4cc9a3d255; i-wanna-go-back=-1; DedeUserID=1111111111111111; DedeUserID__ckMd5=xxxxxxxxxxxxxxx; SESSDATA=xxxxxxx%2C111111111%2Cxxxxx*11; bili_jct=xxxxxxxxxxxxxxxxxxxxxxxx; b_ut=5; fingerprint=23c0ec6ba830169115cc7355f859f977; b_lsid=6B7E865D_181E7E8A5B5; innersign=1; bp_t_offset_357123798=681242105999261730; CURRENT_FNVAL=80; b_timer=%7B%22ffp%22%3A%7B%22333.1007.fp.risk_A7270DDC%22%3A%22181E7E8ADD9%22%2C%22333.788.fp.risk_A7270DDC%22%3A%22181E7E8CE34%22%2C%22777.5.0.0.fp.risk_A7270DDC%22%3A%22181E7EB7DE3%22%2C%22888.2421.fp.risk_A7270DDC%22%3A%22181E7F1ACDB%22%7D%7D; PVID=1`

甚至这个是 `cat_bili_config1.json` 

![image](https://user-images.githubusercontent.com/44313800/178149631-988e030f-9078-4354-a857-fdfeefff5f93.png)

**Comment by Night-stars-1** [comment]
> 这确实令人匪夷所思。
> 
> 更新中有以下两个提交会影响到登录，但是我用了几个账号各种方式获取的 cookie 测试并没有复现这个问题。
> 
> ![image](https://user-images.githubusercontent.com/44313800/178149423-54d1e891-99f4-43ef-860a-f243db26411b.png)
> 
> 我可能需要更多有用的信息，比如使用的完整的 cookie （但是这可能·并没有效果，登录只需要三个字段，只有SESSDATA会出现编码的情况）。类似于下面这样，除了必要的内容 `DedeUserID=1111111111111111; DedeUserID__ckMd5=xxxxxxxxxxxxxxx; SESSDATA=xxxxxxx%2C111111111%2Cxxxxx*11; bili_jct=xxxxxxxxxxxxxxxxxxxxxxxx;` 屏蔽外，其它都保持原状。
> 
> `_uuid=57410536E-54ED-F9FB-E1D6-5F5DD615728333965infoc; buvid4=5A9EF03F-1B37-C000-F9FF-5102AC0A136232033-022030520-VvMikCQsMQZlpg2xGrb53Q%3D%3D; buvid_fp_plain=undefined; CURRENT_BLACKGAP=0; rpdid=|(k))JlJmu~l0J'uYRYR)Rl)|; LIVE_BUVID=AUTO9516464848864875; nostalgia_conf=-1; hit-dyn-v2=1; is-2022-channel=1; blackside_state=0; buvid_fp=ac1cd9b03dee8a9ebdf8f917ed9e8148; CURRENT_QUALITY=120; sid=aask0sb4; buvid3=A7270DDC-668C-414A-8B4F-7C3744100901167636infoc; fingerprint3=1093ceb29f559ff6ab9a3b4cc9a3d255; i-wanna-go-back=-1; DedeUserID=1111111111111111; DedeUserID__ckMd5=xxxxxxxxxxxxxxx; SESSDATA=xxxxxxx%2C111111111%2Cxxxxx*11; bili_jct=xxxxxxxxxxxxxxxxxxxxxxxx; b_ut=5; fingerprint=23c0ec6ba830169115cc7355f859f977; b_lsid=6B7E865D_181E7E8A5B5; innersign=1; bp_t_offset_357123798=681242105999261730; CURRENT_FNVAL=80; b_timer=%7B%22ffp%22%3A%7B%22333.1007.fp.risk_A7270DDC%22%3A%22181E7E8ADD9%22%2C%22333.788.fp.risk_A7270DDC%22%3A%22181E7E8CE34%22%2C%22777.5.0.0.fp.risk_A7270DDC%22%3A%22181E7EB7DE3%22%2C%22888.2421.fp.risk_A7270DDC%22%3A%22181E7F1ACDB%22%7D%7D; PVID=1`
> 
> 甚至这个是 `cat_bili_config1.json`
> 
> ![image](https://user-images.githubusercontent.com/44313800/178149631-988e030f-9078-4354-a857-fdfeefff5f93.png)

刚刚重新获取了一次cookie，仍然无法登陆
v0.5.220708版本登陆失败
v0.5.220706版本登陆失败
v0.5.220628版本登陆成功

cat_bili_config1.json是因为我之前配置了BILITOOLS_FILE_NAME，刚才的测试我已经删除了该变量，并且所有版本运行都来自cat_bili_config.json

![Screenshot_2022-07-10-23-09-00-574_com android chrome](https://user-images.githubusercontent.com/99261160/178150966-b9a433c7-41fd-49c8-9799-fbd2340c8a22.png)
![Screenshot_2022-07-10-23-07-22-891_com android chrome](https://user-images.githubusercontent.com/99261160/178151063-4033c495-c90f-4f84-b327-7caba16cc34a.png)

![IMG_20220710_231004](https://user-images.githubusercontent.com/99261160/178150971-0bb587c4-6676-4f78-adc6-a89c21072d79.jpg)

**Comment by catlair** [comment]
如果 06 也失败，那只能考虑cookie编码的问题了，还是想要知道你的详细 cookie

**Comment by catlair** [comment]
`@catlair/bilitools@0.5.220710-dev.1` 对编码策略进行了调整，不知是否有效，然后他在每次访问 cookie 时都会打印当前携带的cookie

**Comment by Night-stars-1** [comment]
> 

您好，有效，0.5.220710-dev.1版本登陆成功了ヾ(❀╹◡╹)ﾉ~

**Comment by Night-stars-1** [comment]
> `@catlair/bilitools@0.5.220710-dev.1` 对编码策略进行了调整，不知是否有效，然后他在每次访问 cookie 时都会打印当前携带的cookie

您好，有效，0.5.220710-dev.1版本登陆成功了ヾ(❀╹◡╹)ﾉ~

**Comment by Night-stars-1** [comment]
> 如果 06 也失败，那只能考虑cookie编码的问题了，还是想要知道你的详细 cookie

0.5.220710-dev.1版本登陆成功了
如果还需要cookie我可以提供给你

**Comment by catlair** [comment]
> > 如果 06 也失败，那只能考虑cookie编码的问题了，还是想要知道你的详细 cookie
> 
> 0.5.220710-dev.1版本登陆成功了 如果还需要cookie我可以提供给你

如果可以，那再好不过了

**Comment by catlair** [comment]
> > 如果 06 也失败，那只能考虑cookie编码的问题了，还是想要知道你的详细 cookie
> 
> 0.5.220710-dev.1版本登陆成功了 如果还需要cookie我可以提供给你

如果可以，那再好不过了

**Comment by Night-stars-1** [comment]
> > > 如果 06 也失败，那只能考虑cookie编码的问题了，还是想要知道你的详细 cookie
> > 
> > 
> > 0.5.220710-dev.1版本登陆成功了 如果还需要cookie我可以提供给你
> 
> 如果可以，那再好不过了

嗯 我该如何发给你，如果我发在这里别人也可以看见_(´ཀ`」 ∠)__

**Comment by catlair** [comment]
可以按照我上面说的方式，当然如果你要直接发的话，可以https://btdocs.vercel.app/about/加群，或者直接发邮箱 catlair@qq.com
