### ISSUE TITLE
[新增]: 自动积分兑换漫画福利券和参与天选结束后取消关注功能

### ISSUE THREAD

**Issue by wdssfff00** [KudouRan/BiliTools#86]
### 需求是否是平台独享受的

否，全平台均可

### 需求描述

**一、
现在有漫画自动签到功能了，签到积分最划算的是可以用作漫读卷兑换，签到一周基本上就够。兑换一次漫读券，正好可以用作周更漫画的观看。但是每天的漫读卷基本上在3分钟之内就会抢光，希望可以增加个定时兑换功能。**
**二、
天选的关注需求很大，基本上运行几天之后就满2000关注。希望可以增加一个天选位中奖取消关注的功能。**
![Screenshot_2022-07-15-14-29-37-508_com bilibili comic](https://user-images.githubusercontent.com/83413772/179165965-e2015994-dd41-48d9-9466-190d8ea626d4.jpg)
![Screenshot_2022-07-15-14-30-01-775_com bilibili comic](https://user-images.githubusercontent.com/83413772/179165973-19a4ba43-de59-4835-a57b-86c2ea86a2c2.jpg)
。

### 有效的帮助

~~提供以前BiliExper项目对以上两个功能实现示例，望参考。 https://github.com/MaxSecurity/BiliExper~~

**Comment by catlair** [comment]
第一个我不用漫画，不了解情况，所以优先级会很低。

第二个，你可以用各种网页版的脚本清除关注。然后，这个功能存在的，https://github.com/KudouRan/BiliTools/blob/bye/src/task/batchUnfollow.ts 如果配置，他会在取消指定分组的关注，(运行顺序在天选之前)

**Comment by wdssfff00** [comment]
好的，感谢回复

**Comment by catlair** [comment]
功能做出来了，但是这种需要抢时间的和项目格格不入，目前不知道怎么加进去，不过你可以自己导出来使用，举例

阿里云函数

```javascript
const { getBiliTask }  = require('@catlair/bilitools/dist/task');

exports.handler = async () => {
  const mangaTask = await getBiliTask('mangaTask');
  await mangaTask();
}
```

非云函数

```javascript
const { getBiliTask }  = require('@catlair/bilitools/dist/task');

(async () => {
    const mangaTask = await getBiliTask('mangaTask');
    await mangaTask();
})();

```

**Comment by wdssfff00** [comment]
> 功能做出来了，但是这种需要抢时间的和项目格格不入，目前不知道怎么加进去，不过你可以自己导出来使用（怎么定时就看自己，因为本来项目就没提供这个功能），举例
> 
> 配置中
> 
> ```js
> {
> manga: {
>     // 签到
>     sign: true,
>     // 等等配置...
>     // 商城兑换漫读券数量，积分不足算最低
>     exchangeCouponNum: 0,
>   },
> }
> ```
> 
> 阿里云函数
> 
> ```js
> const { getBiliTask }  = require('@catlair/bilitools/dist/task');
> 
> exports.handler = async () => {
>   const mangaTask = await getBiliTask('mangaTask');
>   await mangaTask();
> }
> ```
> 
> 非云函数
> 
> ```js
> const { getBiliTask }  = require('@catlair/bilitools/dist/task');
> 
> (async () => {
>     const mangaTask = await getBiliTask('mangaTask');
>     await mangaTask();
> })();
> ```
> 
> 如果有啥好的想法也可以说

的确，如果要实现的话需要正午12点运行，但这也会让别的任务也运行，我想到的也是把上面的写进配置里然后添加一个12点运行定时，如果其他时间运行就领取失败便是。（或者写个判断？if现在处于配置里指定时间to运行 exchangeCouponNum: 0,  不过感觉挺麻烦的。。。。。）

**Comment by KudouRan** [comment]
这里有个奇怪的现象，12:00:39 出现人太多，12:00:40 库存不足。12:00:48 人太多，12:00:50 成功。

```bash
[verbose 2022/7/21 12:00:34] 读取配置文件 /home/catlair/github/BiliTools/config/config.dev.json5
[👻 2022/7/21 12:00:38] 当前版本【v0.4.12】
[👻 2022/7/21 12:00:39] 可更新：最新版本【v0.5.220711】
[👻 2022/7/21 12:00:39] 开始执行自定义任务！
[👻 2022/7/21 12:00:39] ----【漫画任务】----
[👻 2022/7/21 12:00:39] 开始兑换漫读券，预设数量：1
[👻 2022/7/21 12:00:39] 当前积分：430
[❔ 2022/7/21 12:00:39] 兑换商品请求失败：4 现在抢票的人太多啦，再点一下有机会优先上车喔 ε=ε=(ノ≧∇≦)ノ
[👻 2022/7/21 12:00:39] 开始兑换漫读券，预设数量：1
[👻 2022/7/21 12:00:40] 当前积分：430
[❔ 2022/7/21 12:00:40] 兑换商品请求失败：2 库存不足
[👻 2022/7/21 12:00:40] 开始签到
[👻 2022/7/21 12:00:40] 已经签到过了，跳过任务
[👻 2022/7/21 12:00:40] ----【消息推送】----
```

```bash
[verbose 2022/7/21 12:00:43] 读取配置文件 /home/catlair/github/BiliTools/config/config.dev.json5
[👻 2022/7/21 12:00:48] 当前版本【v0.4.12】
[👻 2022/7/21 12:00:48] 可更新：最新版本【v0.5.220711】
[👻 2022/7/21 12:00:48] 开始执行自定义任务！
[👻 2022/7/21 12:00:48] ----【漫画任务】----
[👻 2022/7/21 12:00:48] 开始兑换漫读券，预设数量：1
[👻 2022/7/21 12:00:48] 当前积分：430
[❔ 2022/7/21 12:00:48] 兑换商品请求失败：4 现在抢票的人太多啦，再点一下有机会优先上车喔 ε=ε=(ノ≧∇≦)ノ
[👻 2022/7/21 12:00:49] 开始兑换漫读券，预设数量：1
[👻 2022/7/21 12:00:49] 当前积分：430
[❔ 2022/7/21 12:00:49] 兑换商品请求失败：4 现在抢票的人太多啦，再点一下有机会优先上车喔 ε=ε=(ノ≧∇≦)ノ
[👻 2022/7/21 12:00:49] 开始兑换漫读券，预设数量：1
[👻 2022/7/21 12:00:49] 当前积分：430
[❔ 2022/7/21 12:00:49] 兑换商品请求失败：4 现在抢票的人太多啦，再点一下有机会优先上车喔 ε=ε=(ノ≧∇≦)ノ
[👻 2022/7/21 12:00:50] 开始兑换漫读券，预设数量：1
[👻 2022/7/21 12:00:50] 当前积分：430
[👻 2022/7/21 12:00:50] 兑换商品成功，兑换数量：1
[👻 2022/7/21 12:00:50] 开始签到
[👻 2022/7/21 12:00:50] 已经签到过了，跳过任务
[👻 2022/7/21 12:00:50] ----【消息推送】----
```
