### ISSUE TITLE
[新增]: 能否新增对天选中奖的消息通知

### ISSUE THREAD

**Issue by Ariaxi** [KudouRan/BiliTools#92]
### 需求是否是平台独享受的

否

### 需求描述

我想。。。

### 有效的帮助

可参考(https://github.com/MaxSecurity/BiliExper/blob/master/tasks/msg_notify_task.py)  ？
另外天选关注的消息没有阅读，每次都有未阅读消息提示。

**Comment by KudouRan** [comment]
消息阅读是存在连续大量没有阅读还是间隔部分没有阅读。

如果是间隔，原因是：消息阅读是根据天选关注的人进行的，获取天选关注的人并不准确，有的可能是需要同时关注多人才行，额外的关注就无法被记录到，还有可能存在其他原因。

**Comment by KudouRan** [comment]
看到有人说天选接口有变化，不知道是不是真的，如果是就先不用了

**Comment by Ariaxi** [comment]
> 看到有人说天选接口有变化，不知道是不是真的，如果是就先不用了

貌似没变，刚测试下
![image](https://user-images.githubusercontent.com/37653613/180419367-8db6277e-da54-4262-94ce-c35fe200803d.png)

**Comment by KudouRan** [comment]
> > 看到有人说天选接口有变化，不知道是不是真的，如果是就先不用了
> 
> 貌似没变，刚测试下 ![image](https://user-images.githubusercontent.com/37653613/180419367-8db6277e-da54-4262-94ce-c35fe200803d.png)

嗯

**Comment by KudouRan** [comment]
(https://github.com/MaxSecurity/BiliExper/blob/master/tasks/msg_notify_task.py)  这个链接是读取未读信息，感觉不如直接打开 b 站看

**Comment by Ariaxi** [comment]
> 
是的，可以从未读信息读取的       17561219: "直播小喇叭"   中奖消息。
emmm，直接打开B站要切号，每天重复操作的话还是比较麻烦。

**Comment by Ariaxi** [comment]
> (https://github.com/MaxSecurity/BiliExper/blob/master/tasks/msg_notify_task.py) 这个链接是读取未读信息，感觉不如直接打开 b 站看

是的，可以从未读信息读取的 17561219: "直播小喇叭" 中奖消息。
emmm，直接打开B站要切号，每天重复操作的话还是比较麻烦。
