### ISSUE TITLE
[新增]: 腾讯云函数视频

### ISSUE THREAD

**Issue by cao-gift** [KudouRan/BiliTools#96]
### 需求是否是平台独享受的

腾讯云函数

### 需求描述

帮你录的腾讯云函数视频
https://www.bilibili.com/video/bv1eW4y127PM

**Comment by KudouRan** [comment]
感谢，已添加到文档

https://github.com/KudouRan/btdocs/commit/2d9de144a87809ad2b8a524492a7f6e8ccd89243
