### ISSUE TITLE
log文件有点臃肿

### ISSUE THREAD

**Issue by wdssfff00** [KudouRan/BiliTools#99]
### 需求是否是平台独享受的

是，非云函数环境

### 需求描述

log每次输出都是在同一个文件里，
长期运行文件臃肿，现在看日志出现困难，
建议改成每次输出不同文件或者按天输出。

**Comment by catlair** [comment]
日志并不是在一个文件，而且一个月一个文件

**Comment by wdssfff00** [comment]
了解了

**Comment by catlair** [comment]
![image](https://user-images.githubusercontent.com/44313800/181444202-0951c3ec-e43c-4e82-9dd9-c4724d7fc862.png)

![image](https://user-images.githubusercontent.com/44313800/181444349-3567c466-c1ab-4cb2-a26a-c4972972ba73.png)

bt_combined-def 文件是不可控的，因为这个文件的内容可能产生于配置加载前
